# Generated by Django 3.0 on 2021-10-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=699.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='storage',
            field=models.IntegerField(default=256),
            preserve_default=False,
        ),
    ]
