# Generated by Django 3.0 on 2021-10-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='base_model',
        ),
    ]
