# Generated by Django 3.2.6 on 2021-10-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211025_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='device',
        ),
    ]
